leftnav:
- identifier: 5e3e7c74-5a38-4d45-ad7d-78e7e1eaedb0
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 035994aa-68b0-4602-8ac5-cedd472369fa
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 74a3de58-e4e8-4eae-8aef-497a93af2028
  name: Instructor Insights
  pageRef: /pages/class-7-joint-distributions-independence-covariance-and-correlation
  weight: 30
- identifier: ec1e33f0-a454-45c4-80ef-fb58703d8516
  name: Readings
  pageRef: /pages/studio-4
  weight: 40
- identifier: 23e8a908-5983-495b-b439-5c598e3b6bfb
  name: Class Slides
  pageRef: /lists/class-slides
  weight: 50
- identifier: 60b6afbc-30d9-4852-ad59-e669be63c8f1
  name: Problem Sets
  pageRef: /pages/exam-1
  weight: 60
- identifier: 2b028d93-8561-4c84-9ece-b01d0c4f191a
  name: Exams
  pageRef: /pages/unit-2-statistics-bayesian-inference
  weight: 70
- identifier: d1616c8c-ad0b-4679-b5a8-4001eaeef45a
  name: Studio Resources
  pageRef: /pages/unit-3-statistics-frequentist-inference-nhst
  weight: 80
- identifier: c87974e0-c253-4a50-8148-0b92730b0131
  name: Related Resources
  pageRef: /pages/unit-4-statistics-confidence-intervals-regression
  weight: 90
